# Generated by Django 2.0.7 on 2018-08-07 21:57

import courses.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180808_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('main', 'Main'), ('sec', 'Secondary')], default='main', max_length=120),
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=courses.fields.PositionField(default=-1),
        ),
    ]
