# Generated by Django 2.0.7 on 2018-08-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('courses', '0013_auto_20180810_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='secondary',
            field=models.ManyToManyField(blank=True, related_name='secondary_category', to='categories.Category'),
        ),
    ]
