# Generated by Django 2.0.7 on 2018-08-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20180803_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='member_required',
            field=models.BooleanField(default=False),
        ),
    ]
